server:
  port: 9999

spring:
  application:
    title: Clean Architecture
    name: Sample
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: DETECT

datasource:
  account:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password


logging:
  #pattern:
  #console: "[%-5level %d{yyyy-MM-dd HH:mm:ss}] [%-8thread] [%logger{0}:%line] - %msg%n"
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: DEBUG
      leezxczxc: DEBUG